version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=appsilon.app:create_app
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=postgres
      - DB_HOST=db
      - DB_PORT=5433
      - REBUILD_DB=false
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: sh -c 'if [ "$REBUILD_DB" = "true" ]; then make build-db && make run; else make run; fi'

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5433
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5433:5433"
    command: -p 5433
    expose:
      - "5433"

volumes:
  db_data:
